[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.11"
show_error_context = true
show_column_numbers = true
show_error_codes = true
pretty = true